= Предоставление доступа к {of-mc}

_Администратор {of-mc}_ -- пользователь, добавленный в группу _{dv-web-admin-cns-admins-serv}_ в конфигурационном файле {of-mc}. Администратор имеет полный доступ к изменению настроек Консоли, конфигурации _{of-sett-serv}_, а также ко всем функциям модуля.

// tag::config[]
[source,json]
----
{
  "Groups": {
    "Docsvision Management Console Administrators": [
      "account@domain.com" <.>
    ]
  }
}
----
<.> Добавьте пользователей, которые должны иметь доступ к {of-mc}.
// end::config[]

Добавление пользователя в группу _{dv-web-admin-cns-admins-serv}_ в конфигурационном файле модуля {pl} предоставляет доступ к просмотру карточек сообщений, но не даёт доступа в {mc}:

.Фрагмент конфигурационного файла модуля {pl}:
[source,json]
----
{
  "DocsVision": {
  "Groups": {
    "DocsVision Management Console Administrators": [
      "domain\\account"
    ], <.>
    "DocsVision Security Administrators": [
      "domain\\account"
    ]
  },
}
----
<.> Добавьте пользователей, которые должны иметь доступ сообщениям карточек.

ifndef::windows[]
// tag::keytab[]
NOTE: При необходимости может быть настроена прозрачная аутентификация Kerberos, необходимые настройки см. в разделе "xref:dv6@engineer:ROOT:kerberos-authentication.adoc[]".
// end::keytab[]
endif::windows[]
