= Предоставление доступа к {of-mc}

_Администратор {of-mc}_ -- пользователь, добавленный в группу *{dv-web-admin-cns-admins-serv}* в конфигурационном файле модуля {pl}. Администратор имеет полный доступ к изменению настроек Консоли, конфигурации _{of-sett-serv}_, а ко всем функциям модуля. Назначить пользователя администратором можно отредактировав конфигурационный модуля {pl}:

// tag::config[]
.Фрагмент конфигурационного файла модуля {pl}:
[source,json]
----
{
  "DocsVision": {
  "Groups": {
    "DocsVision Management Console Administrators": [
      "domain\\account"
    ], <.>
    "DocsVision Security Administrators": [
      "domain\\account"
    ]
  },
}
----
<.> Добавьте пользователей, которые должны иметь доступ к {of-mc}.
// end::config[]

Добавление пользователя в группу *{dv-web-admin-cns-admins-serv}* в конфигурационном файле {of-mc} предоставляет доступ к просмотру карточек сообщений, но не даёт доступа в {mc}:

[source,json]
----
{
  "Groups": {
    "Docsvision Management Console Administrators": [
      "account@domain.com" <.>
    ]
  }
}
----
<.> Добавьте пользователей, которые должны иметь доступ сообщениям карточек.

ifndef::windows[]
// tag::keytab[]
NOTE: При необходимости может быть настроена прозрачная аутентификация Kerberos, необходимые настройки см. в разделе "xref:dv6@engineer:ROOT:kerberos-authentication.adoc[]".
// end::keytab[]
endif::windows[]
